default: &default
  base_url: 'http://localhost:3000'
  admin:
    - name: "admin"
    # or
    - email: "admin@qq.com"
    # or
    - phone: "13988887777"
    # or
    - phone: "13988887777"
      name: "admin"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default